cache:
    paths:
    - node_modules/
stages:
    - test
    - build
    - deploy
test:
    stage: test
    script:
        - echo "test stage"
        - npm install
        - npm run test
    tags:
        - pers
build:
    stage: build
    script: 
        - echo "build stage"
        - npm run build 
        - pwd
        - ls
    tags:
        - pers

deploy:
    stage: deploy
    script: echo "deploy stage"
        - echo "deploy stage"
        - npm run deploy
    tags:
        - pers
